import { ACTION_ADD, ACTION_EDIT, ACTION_REMOVE, ACTION_UP, ACTION_DOWN } from './actions.consts';

export const RECORD_ACTIONS = [
    ACTION_ADD, ACTION_EDIT, ACTION_REMOVE, ACTION_UP, ACTION_DOWN
];

