export enum E_RECORD_ACTIONS {
    add,
    edit,
    view,
    remove,
    removeHard,
    order,
    userOrder,
    quickSearch,
    fullSearch,
    import,
    export,
    markRecords,
    unmarkRecords,
    sorting,
    navigateUp,
    navigateDown,
    restore,
    /* to be extended */
};
